
set(CPACK_PACKAGE_EXECUTABLES
    "GuiLibDemo;GUI Lib Demo"
	)
set(CPACK_PACKAGE_NAME "${CMAKE_PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR "Somfy")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${CMAKE_PROJECT_NAME}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/COPYING")
set(CPACK_PACKAGE_VERSION_MAJOR "${VER_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${VER_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${VER_PATCH}")
set(CPACK_PACKAGE_CONTACT "Frederic Vulliet <frederic.vulliet@somfy.com>")

set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)

if(WIN32)
    set(CPACK_NSIS_DEFINES "!define MUI_STARTMENUPAGE_DEFAULTFOLDER \\\"Somfy\\\"")
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "Somfy\\\\${CPACK_PACKAGE_NAME}-${VERSION}")
    set(CPACK_NSIS_DISPLAY_NAME "${CMAKE_PROJECT_NAME}")

    add_custom_target(PackBundle
            COMMAND ${CMAKE_COMMAND} ${CMAKE_SOURCE_DIR} -P ${CMAKE_BINARY_DIR}/PackBundle.cmake)
    set(CPACK_INSTALL_COMMANDS
        "${CMAKE_COMMAND} ${CMAKE_SOURCE_DIR} -DPACK_INSTALLED=ON -P ${CMAKE_BINARY_DIR}/PackBundle.cmake")
endif(WIN32)

include("${CMAKE_CURRENT_LIST_DIR}/PackScript.cmake")
include(CPack)

configure_file("${CMAKE_CURRENT_LIST_DIR}/PackBundle.cmake.in" PackBundle.cmake @ONLY)

