
find_program(QMLTESTRUNNER_EXE qmltestrunner)
set(QMLTESTRUNNER_TEMPLATE ${CMAKE_CURRENT_LIST_DIR}/QMLTestRunner.cpp)
function(QMLTESTRUNNER TARGET)
    cmake_parse_arguments(TESTRUNNER "" "WORKING_DIRECTORY;IMPORT_PATH" "" ${ARGN})
    if(NOT TESTRUNNER_WORKING_DIRECTORY)
        set(TESTRUNNER_WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
    endif()

    add_executable(${TARGET} ${QMLTESTRUNNER_TEMPLATE} ${TESTRUNNER_UNPARSED_ARGUMENTS})
    target_link_libraries(${TARGET} ${QT_LIBRARIES})
    qt_use_modules(${TARGET} Core)
    set_target_properties(${TARGET} PROPERTIES
            COMPILE_DEFINITIONS "QML2_IMPORT_PATH=\"${TESTRUNNER_IMPORT_PATH}\";WORKDIR=\"${TESTRUNNER_WORKING_DIRECTORY}\";QMLTESTRUNNER=\"${QMLTESTRUNNER_EXE}\"")
endfunction(QMLTESTRUNNER)

